stages:
  - test

.unit-test: &unit
  stage: test
  image: python:3
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  script:
    - tox --skip-missing-interpreters -- -qqrf
  before_script:
    - python -V
    - pip install -r requirements.txt
    - pip install -e .
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

test-local-coverage:
  <<: *unit
  script:
    - pip install pytest-cov
    - pytest -qq --cov=openpyxl --cov-report=xml --cov-report=term
  coverage: '/^TOTAL.+?(\d+\%)$/'

  artifacts:
    reports:
      cobertura: coverage.xml